version: '3.8'

services:
  # Servicio de Laravel (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - mysql
      - redis
    ports:
      - "8000:9000"
    environment:
      - "DB_HOST=mysql"
      - "DB_PORT=3306"
      - "DB_DATABASE=laravel_db"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=root"
      - "REDIS_HOST=redis"
      - "QUEUE_CONNECTION=redis"

  # Servicio de MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

  # Servicio de Redis
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - app-network
    ports:
      - "6379:6379"

  # Servicio de Nginx (para servir la app Laravel)
  nginx:
    image: nginx:alpine
    container_name: nginx-server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www
    networks:
      - app-network
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
